CodeforeveryoneSeoul/codeforeveryone

readme.md
@RachellCalhoun if this looks good, comment below and press the green button!
=> initial readme for setting up

landingsite/views.py
I am using gmail smtp - Although I have setup from_email (get from the form) but still from email is gmail used for setting up smtp. Therefore I appended it in message. Please review or suggest alternative.
=> fixed an issue with gmail smtp. Included from_email in message

code4every1site/context_processors.py, code4every1site/settings.py, code4every1site/templates/base.html
Adds the git hash to the footer so we can keep track of what is deployed easily
=> add context processor and githash to base template

readme.md
Just updating the readme so people know we use the github flow method
Also this will test the travis ci integration and auto deploy as mentioned in #24
=> mention github flow in readme and add svg link to travis

.travis.yml, code4every1site/settings.py
Found a few issues with the deployment. 
This fixes git hash problem, and the ssh key problem
=> Fix travis ci deployment

landingsite/templates/landingsite/contact_us.html
=> super easy client side validation for contact page

code4every1site/urls.py, landingsite/templates/landingsite/contact_us.html, landingsite/urls.py, landingsite/views.py
Basically I want to hit /contact-us/email/ for POST data.
I am getting following error :   
NoReverseMatch at /contact-us/
Reverse for 'contact' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['$contact-us/email/$']
=> create a separate view for email post data - It is not working somehow

code4every1site/templates/base.html, hacks/templates/hacks/hacks_home.html, landingsite/templates/landingsite/about_us.html, landingsite/templates/landingsite/contact_us.html, landingsite/templates/landingsite/index.html, landingsite/templates/landingsite/thanks.html
Also cleaned up the footer so it doesnt take up so much space
Also removed the sidebar for the about page beucase it wasnt really adding anything :P
=> removed commented out html, and weird unused images

landingsite/tests.py
We should wait for #31 but this PR will probably fail when that gets merged :)
I'll fix it when that happens
=> add tests for email

code4every1site/templates/base.html, landingsite/static/landingsite/css/styles.css, landingsite/templates/landingsite/index.html
I changed the font of nonprofit on index page, and deleted the search from header.
=> deleted search button, edited nonprofit font, added s

code4every1site/settings.py
Add Secure SSL Redirect  Reference : https://docs.djangoproject.com/en/1.8/topics/security/#ssl-https
Fix #38
=> add ssl secure redirect - fix #38

landingsite/templates/landingsite/contact_us.html
#34 I didn't want to pull my hair out, so I did what I could. check it out.
=> edited spacing/format but cant elongate message

code4every1site/settings.py
I have this manually changed in prod to get https working but we need this committed so this stays working
=> add hosts to settings

readme.md, release.md
=> add info about how our releases work

landingsite/templates/landingsite/index.html
subtitle Title of the page: made it two lines. I changed the second section label to 'teach and learn' I thought we can add more info later/link to the weekly meetups page once it's ready. I also put a space for workshop/hakathon it was bothering me on mobile.
=> changed label format and spacing

accounts/admin.py, accounts/forms.py, accounts/models.py, accounts/templates/registration/login.html, accounts/templates/registration/register.html, accounts/templatetags/form_tags.py, accounts/tests.py, accounts/urls.py, accounts/views.py, code4every1site/settings.py, code4every1site/templates/base.html, code4every1site/urls.py, landingsite/static/landingsite/css/messages.css
Adds login and register with tests
Still more work needs to be done but this is in a "working" state
Ref: #3 1st part in checklist
=> add login and register with tests

.gitignore
=> add logs to gitignore

code4every1site/settings.py, code4every1site/urls.py, requirements.txt, rsvp/admin.py, rsvp/migrations/0008_auto_20151022_1402.py, rsvp/models.py, rsvp/templates/rsvp/event_detail.html
Adds django markdown to event notes
=> add django-makrdown

code4every1site/templates/base.html
=> remove viewsoure button

rsvp/static/rsvp/css/event_detail.css, rsvp/templates/rsvp/event_detail.html
Remove previous #72  and consider this one
=> add material icons for notes and time

code4every1site/templates/base.html
Let me know what and if I should delete more stuff.
=> deleted contact us from menus

code4every1site/templates/base.html
added source button to footer. #82
=> added source button to footer
